Feat/role access fix
Dresh13/CS_361_project pull request #51
Opened 2023-12-16 20:04 UTC by Dresh13

double check over to ensure correct access requirements

2023-12-16 20:10 UTC, N7Ironclad requested changes

2023-12-16 20:10 UTC, N7Ironclad commented on supercreative/views.py
> +        role = request.session['role']
request.session also contains an email key. Can you use that to verify that the claimed role matches the user's assigned role by filtering with their email? It should typically match up but if it ever didn't match up we shouldn't allow them to proceed with an incorrect role.

2023-12-18 23:44 UTC, Dresh13 commented on supercreative/views.py
> +        role = request.session['role']
are we using cookie based sessions or server side? if we simply switched to server side we wouldn't have a security risk

2023-12-19 03:04 UTC, N7Ironclad approved these changes

2023-12-19 03:09 UTC, brogers32 approved these changes

2023-12-19 03:16 UTC, merged